version: '3.8'

services:
  # PostgreSQL Database with pgvector
  postgres:
    image: pgvector/pgvector:pg17
    container_name: icarus-postgres
    environment:
      POSTGRES_DB: icarusdb
      POSTGRES_USER: icarususer
      POSTGRES_PASSWORD: icaruspass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icarususer -d icarusdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Rust Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: icarus-backend
    environment:
      DATABASE_URL: postgresql://icarususer:icaruspass@postgres:5432/icarusdb
      RUST_LOG: debug
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Svelte Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: icarus-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  postgres_data:
