[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
limbo = "0.0.17"
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-cors = "0.7.1"
